python train_gen.py \
--batch-size 32 \
--ndiscriminators 8 \
--im-size 200 \
--n-balls 3 \
--n-frames 30 \
--n-examples 50000 \
--workers 8 \
--checkpoint-path ./cp/gen \
--epochs 200 \
--checkpoint-epoch 100 \
--logdir /media/joaomonteirof/SSD1/logs/cup_gen
